# Generated by Django 5.2 on 2025-04-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JEEPdfUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_key', models.FileField(upload_to='answer_keys/')),
                ('student_response', models.FileField(upload_to='student_responses/')),
                ('pattern_q', models.IntegerField(default=0, help_text='Question pattern adjustment')),
                ('pattern_a', models.IntegerField(default=0, help_text='Answer pattern adjustment')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
