# Generated by Django 5.2 on 2025-04-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeecalculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JEEScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('total_score', models.FloatField(default=0.0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('unattempted_questions', models.IntegerField(default=0)),
                ('math_score', models.IntegerField(default=0)),
                ('physics_score', models.IntegerField(default=0)),
                ('chemistry_score', models.IntegerField(default=0)),
            ],
        ),
    ]
