# Generated by Django 5.2 on 2025-04-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeecalculator', '0002_jeescores'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeescores',
            name='test_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jeescores',
            name='test_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
